import * as THREE from 'three';
export function createScene(canvas,{mode='dive',onStatus=()=>{},reduced=false}={}){
 let renderer,alive=true,visible=true,progress=0,explosion=0,selected=-1,frame=0;
 const fallback={available:false,update(){},setReduced(){},explode(){},select(){}};
 try{renderer=new THREE.WebGLRenderer({canvas,antialias:true,alpha:true,powerPreference:'low-power'});}catch(e){canvas.hidden=true;onStatus('АРХИВНЫЙ КАДР / 3D НЕДОСТУПНО');return fallback;}
 const scene=new THREE.Scene();scene.fog=new THREE.FogExp2(0x071b2b,.025);
 const camera=new THREE.PerspectiveCamera(38,1,.1,100);camera.position.set(6.4,3.5,8.8);camera.lookAt(0,0,0);
 renderer.setPixelRatio(Math.min(devicePixelRatio,1.75));renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.45;
 scene.add(new THREE.HemisphereLight(0xa9dcee,0x152835,2.8));const key=new THREE.DirectionalLight(0xb4e2ff,4);key.position.set(4,7,7);scene.add(key);const rim=new THREE.DirectionalLight(0x3977aa,4);rim.position.set(-5,2,-5);scene.add(rim);const orangeLight=new THREE.PointLight(0xee8050,12,16);orangeLight.position.set(-3,4,3);scene.add(orangeLight);
 const metal=new THREE.MeshStandardMaterial({color:0x8fa5ad,metalness:.78,roughness:.3});const dark=new THREE.MeshStandardMaterial({color:0x15242d,metalness:.7,roughness:.5});const orange=new THREE.MeshStandardMaterial({color:0xc96332,metalness:.25,roughness:.6});const glass=new THREE.MeshPhysicalMaterial({color:0x123b51,metalness:.25,roughness:.11,clearcoat:1,transparent:true,opacity:.88});const lightMat=new THREE.MeshBasicMaterial({color:0xcaf3ff});
 const sub=new THREE.Group();scene.add(sub);const systems=Array.from({length:4},()=>new THREE.Group());systems.forEach(g=>sub.add(g));
 const sphere=(radius,mat,pos,scale=[1,1,1],group=systems[0])=>{const m=new THREE.Mesh(new THREE.SphereGeometry(radius,40,24),mat);m.position.set(...pos);m.scale.set(...scale);group.add(m);return m;};
 const box=(size,mat,pos,group)=>{const m=new THREE.Mesh(new THREE.BoxGeometry(...size),mat);m.position.set(...pos);group.add(m);return m;};
 const tube=(a,b,r,mat,group=systems[0])=>{const av=new THREE.Vector3(...a),bv=new THREE.Vector3(...b),d=bv.clone().sub(av);const m=new THREE.Mesh(new THREE.CylinderGeometry(r,r,d.length(),12),mat);m.position.copy(av.add(bv).multiplyScalar(.5));m.quaternion.setFromUnitVectors(new THREE.Vector3(0,1,0),d.normalize());group.add(m);return m;};
 sphere(1.05,metal,[0,.15,0],[1,1,1]);const rearHull=new THREE.Mesh(new THREE.CylinderGeometry(.68,.68,1.3,40),metal);rearHull.rotation.z=Math.PI/2;rearHull.position.set(-.8,.15,0);systems[0].add(rearHull);sphere(.79,glass,[1.19,.16,0],[.46,1,1]);const ring=new THREE.Mesh(new THREE.TorusGeometry(.78,.095,12,64),metal);ring.rotation.y=Math.PI/2;ring.position.set(1.2,.16,0);systems[0].add(ring);
 for(let i=0;i<16;i++){const a=i/16*Math.PI*2;sphere(.047,dark,[1.29,.16+Math.sin(a)*.79,Math.cos(a)*.79]);}
 box([2.9,.3,1.9],dark,[-.1,-.94,0],systems[0]);for(const z of [-.96,.96]){tube([-1.8,-1.18,z],[1.8,-1.18,z],.055,metal);tube([-1.4,-.8,z],[-1.4,-1.18,z],.05,metal);tube([1.25,-.8,z],[1.25,-1.18,z],.05,metal);}
 for(const z of [-.86,.86]){box([1.75,.66,.58],orange,[-.35,1.16,z],systems[1]);for(const x of [-.92,.28])box([.085,.7,.62],dark,[x,1.16,z],systems[1]);}box([.55,.45,1.1],orange,[-1.26,.62,0],systems[1]);
 const propellers=[];for(const [x,y,z] of [[-.95,-.2,-1.36],[-.95,-.2,1.36],[-1.72,.25,-.72],[-1.72,.25,.72]]){const m=new THREE.Mesh(new THREE.CylinderGeometry(.35,.35,.52,32,1,true),dark);m.rotation.z=Math.PI/2;m.position.set(x,y,z);systems[2].add(m);const rr=new THREE.Mesh(new THREE.TorusGeometry(.35,.045,8,32),metal);rr.rotation.y=Math.PI/2;rr.position.set(x+.28,y,z);systems[2].add(rr);const p=new THREE.Group();p.position.set(x+.25,y,z);for(let a=0;a<3;a++){const blade=box([.045,.25,.11],metal,[0,.12,0],p);blade.rotation.x=a*Math.PI*2/3;blade.position.y=Math.cos(a*Math.PI*2/3)*.14;blade.position.z=Math.sin(a*Math.PI*2/3)*.14;}systems[2].add(p);propellers.push(p);tube([x,y,z],[x,y,z*.7],.07,metal,systems[2]);}
 for(const z of [-.82,.82]){const vertical=new THREE.Mesh(new THREE.CylinderGeometry(.26,.26,.35,28,1,true),dark);vertical.position.set(-.6,1.4,z);systems[2].add(vertical);const vr=new THREE.Mesh(new THREE.TorusGeometry(.26,.04,8,32),metal);vr.rotation.x=Math.PI/2;vr.position.set(-.6,1.59,z);systems[2].add(vr);const vp=new THREE.Group();vp.position.set(-.6,1.56,z);vp.rotation.z=Math.PI/2;for(let a=0;a<3;a++){const vb=box([.035,.18,.08],metal,[0,Math.cos(a*Math.PI*2/3)*.1,Math.sin(a*Math.PI*2/3)*.1],vp);vb.rotation.x=a*Math.PI*2/3;}systems[2].add(vp);propellers.push(vp);}
 const highlight=new THREE.BoxHelper(systems[0],0xf18458);highlight.material.transparent=true;highlight.material.opacity=.36;highlight.visible=mode==='vehicle';scene.add(highlight);
 const beams=[];for(const z of [-.75,.75]){sphere(.17,metal,[1.22,-.62,z], [1,1,1],systems[3]);sphere(.12,lightMat,[1.38,-.63,z],[.45,1,1],systems[3]);const cone=new THREE.Mesh(new THREE.ConeGeometry(1.35,5.3,32,1,true),new THREE.MeshBasicMaterial({color:0x83cbee,transparent:true,opacity:.055,depthWrite:false,side:THREE.DoubleSide,blending:THREE.AdditiveBlending}));cone.rotation.z=Math.PI/2;cone.position.set(4,-1.05,z);systems[3].add(cone);beams.push(cone);}tube([.4,1.03,0],[.4,1.43,0],.08,metal,systems[3]);sphere(.17,dark,[.4,1.5,0],[1.4,1,1],systems[3]);sphere(.075,lightMat,[.56,1.5,0],[.45,1,1],systems[3]);
 const pointsCount=mode==='dive'?900:200;const pos=new Float32Array(pointsCount*3);let seed=42;const rand=()=>{seed=(seed*1664525+1013904223)>>>0;return seed/4294967296;};for(let i=0;i<pointsCount;i++){pos[i*3]=(rand()-.5)*32;pos[i*3+1]=(rand()-.5)*22;pos[i*3+2]=(rand()-.5)*24;}const pg=new THREE.BufferGeometry();pg.setAttribute('position',new THREE.BufferAttribute(pos,3));const particles=new THREE.Points(pg,new THREE.PointsMaterial({color:0x91cfdf,size:.024,transparent:true,opacity:.45}));scene.add(particles);
 const floor=new THREE.Group();scene.add(floor);const plane=new THREE.Mesh(new THREE.PlaneGeometry(60,60,24,24),new THREE.MeshStandardMaterial({color:0x34464c,roughness:1}));plane.rotation.x=-Math.PI/2;floor.add(plane);for(let i=0;i<45;i++){const rock=new THREE.Mesh(new THREE.DodecahedronGeometry(.1+rand()*.5,0),new THREE.MeshStandardMaterial({color:0x2a3d45,roughness:1}));rock.position.set((rand()-.5)*25,.1,(rand()-.5)*25);rock.scale.set(1.8,.45,1.2);floor.add(rock);}floor.position.y=-30;
 const jellyGroup=new THREE.Group();scene.add(jellyGroup);for(let i=0;i<7;i++){const j=new THREE.Group();const cap=new THREE.Mesh(new THREE.SphereGeometry(.22,24,12,0,Math.PI*2,0,Math.PI/2),new THREE.MeshBasicMaterial({color:0x7fe4f0,transparent:true,opacity:.2,side:THREE.DoubleSide}));j.add(cap);for(let k=0;k<6;k++){const pts=[];for(let q=0;q<15;q++)pts.push(new THREE.Vector3(Math.sin(q*.55+k)*.045+Math.cos(k)*.12,-q*.045,Math.sin(k)*.12));j.add(new THREE.Line(new THREE.BufferGeometry().setFromPoints(pts),new THREE.LineBasicMaterial({color:0x7fdfef,transparent:true,opacity:.35})));}j.position.set(-4+rand()*8,-3+rand()*6,-3-rand()*4);jellyGroup.add(j);}jellyGroup.visible=false;
 const resize=()=>{const r=canvas.getBoundingClientRect();if(!r.width||!r.height)return;renderer.setSize(r.width,r.height,false);camera.aspect=r.width/r.height;camera.updateProjectionMatrix();draw();};
 const apply=()=>{if(mode==='dive'){const narrow=innerWidth<700;sub.position.set(narrow?0:1.6,.2-progress*1.5,0);sub.rotation.set(.06+Math.sin(progress*Math.PI)*.1,-.6+progress*1.1,-.08+Math.sin(progress*Math.PI*2)*.13);sub.scale.setScalar(narrow?.83:1);camera.position.set(narrow?7.8:6.4,3.8-progress*1.4,narrow?12.8:9);camera.lookAt(narrow?0:1,-.1,0);scene.fog.color.setHSL(.56,.58,.035+(1-progress)*.09);scene.fog.density=.015+progress*.022;key.intensity=4-progress*2.5;floor.position.y=-30+progress*27;floor.visible=progress>.76;jellyGroup.visible=progress>.28&&progress<.8;jellyGroup.position.y=progress*3-1;particles.position.y=(progress*18)%6;beams.forEach(b=>b.material.opacity=.025+progress*.06);}else{camera.position.set(innerWidth<700?8:6.5,3.8,innerWidth<700?11:9);camera.lookAt(0,0,0);sub.rotation.y=-.45;sub.position.y=.1;systems[1].position.y=explosion*1.6;systems[2].position.z=explosion*1.5;systems[2].position.x=-explosion*.9;systems[3].position.x=explosion*1.7;floor.visible=false;jellyGroup.visible=false;sub.updateMatrixWorld(true);highlight.setFromObject(systems[Math.max(0,selected)]);highlight.visible=selected>=0;}}
 function draw(){if(!alive||!visible)return;apply();renderer.render(scene,camera);}
 const tick=()=>{if(!alive)return;frame=requestAnimationFrame(tick);if(!visible||reduced||document.hidden)return;propellers.forEach(p=>p.rotation.x+=.028);if(mode==='vehicle')sub.rotation.z=Math.sin(performance.now()*.0004)*.025;particles.rotation.y+=.00005;draw();};
 const io=new IntersectionObserver(es=>{visible=es[0].isIntersecting;if(visible)draw();},{rootMargin:'100px'});io.observe(canvas);const ro=new ResizeObserver(resize);ro.observe(canvas);canvas.addEventListener('webglcontextlost',e=>{e.preventDefault();alive=false;cancelAnimationFrame(frame);canvas.hidden=true;canvas.closest('.dive-sticky,.vehicle-stage').classList.remove('has-webgl');onStatus('АРХИВНЫЙ КАДР / 3D ПРИОСТАНОВЛЕНО');});addEventListener('pageshow',e=>{if(e.persisted){alive=true;tick();draw();}});addEventListener('pagehide',e=>{alive=false;cancelAnimationFrame(frame);if(e.persisted)return;io.disconnect();ro.disconnect();scene.traverse(o=>{o.geometry?.dispose();if(o.material){(Array.isArray(o.material)?o.material:[o.material]).forEach(m=>m.dispose());}});renderer.dispose();});
 canvas.closest('.dive-sticky,.vehicle-stage').classList.add('has-webgl');onStatus('3D / PROCEDURAL NEREID');resize();tick();return {available:true,update(p){progress=p;draw();},setReduced(v){reduced=v;draw();},explode(v){explosion=v;draw();},select(v){selected=v;draw();}};
}
